---
- name: Update all servers
  hosts: servers
  become: yes
  become_exe: "sudo su"
  become_method: su
  
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"

  - name: Upgrade the OS (ansible.builtin.apt-get dist-upgrade)
    ansible.builtin.apt:
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: Install the packages "cowsay, nmon, tmux, rsync, zip and etc"
    ansible.builtin.apt:
      name: 
        - cowsay
        - nmon
        - tmux
        - rsync
        - zip
        - fortune
        - apache2
      state: latest #abset to remove
    when: ansible_distribution == "Ubuntu"